name: alipay
description: Combined Alipay package (App Pay + QR Pay).
version: 0.1.0
repository: https://github.com/Metaildust/alipay_dart
homepage: https://pub.dev/packages/alipay

environment:
  sdk: ^3.0.0

dependencies:
  alipay_app: ^0.1.0
  alipay_qr: ^0.1.0

dev_dependencies:
  test: ^1.24.0
