name: alipay
description: Combined Alipay package (App Pay + QR Pay).
version: 0.1.0
repository: https://github.com/Metaildust/alipay_dart
homepage: https://pub.dev/packages/alipay

environment:
  sdk: ^3.0.0

dependencies:
  alipay_app:
    path: ../alipay_app
  alipay_qr:
    path: ../alipay_qr

dev_dependencies:
  test: ^1.24.0
