name: alipay_qr
description: Alipay QR Pay precreate and query for Dart/Flutter (server-side).
version: 0.1.0
repository: https://github.com/Metaildust/alipay_dart
homepage: https://pub.dev/packages/alipay_qr

environment:
  sdk: ^3.0.0

dependencies:
  http: ^1.2.0
  pointycastle: ">=3.9.1 <5.0.0"

dev_dependencies:
  test: ^1.24.0
